# Generated by Django 3.1.5 on 2021-02-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0002_auto_20210202_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(default='Not Available', upload_to='static/images'),
            preserve_default=False,
        ),
    ]
