# Generated by Django 3.1.5 on 2021-02-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_auto_20210202_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='image'),
        ),
    ]
